### ISSUE TITLE
CCDA 1.1 Automation: MoodCode affects Semantic Meaning and Mapping

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#5] opened 2015-11-11 18:13 UTC
Moodcode affects the Semantic Meaning, for example a Medication Activity can apply to a variety of activities, such as Administraton, Perscription, or Fullfillment / Dispense. This results in semantically different activities.  The RI will have terms such as MedicationAdministered, MedicationPerscribed, and MedicationDispensed. 

The Automation should be able to generate the map based on the annotation of the MDHT model, set the correct mappings for the Activity and its children, and set the appropriate moodcode value

**Comment by swmuir** [comment] 2015-12-14 14:25
Duplicate of mood code

**Closed by swmuir** 2015-12-14 14:25 UTC
